CREATE TABLE STATS (
                       STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL,
                       PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT TITLE, BESTSELLER FROM KODILLA_COURSE.books;

SELECT * FROM BESTSELLERS_COUNT
WHERE BESTSELLER = 1;

USE KODILLA_COURSE;

CREATE EVENT UPDATE_BESTSELLER
    ON SCHEDULE EVERY 1 MINUTE
    DO BEGIN
    CALL UpdateBestsellerStatus();
    SELECT * FROM BESTSELLERS_COUNT;
    INSERT INTO KODILLA_COURSE.stats (STAT) VALUES ('BESTSELLERS');
    INSERT INTO KODILLA_COURSE.stats (VALUE) VALUES (COUNT (KODILLA_COURSE.books.BESTSELLER));
end;