
EXPLAIN SELECT COUNT(*)
        FROM BOOKS, READERS;

CREATE INDEX CHECKNAME ON READERS(FIRSTNAME);

EXPLAIN SELECT COUNT(*)
        FROM BOOKS, READERS
        WHERE FIRSTNAME = 'John';

ALTER TABLE READERS
    DROP INDEX CHECKNAME;
